const CANVAS_WIDTH = 1920;
const CANVAS_HEIGHT = 1080;
const CANVAS_FONT = "'Noto Sans JP', sans-serif";
const TAG_AREA_WIDTH = 480;
const TAG_AREA_POSITION_X = 35;
const TAG_AREA_POSITION_Y = 35;
const TAG_AREA_INNER_PADDING = 20;
